### PR TITLE
Add Clasp support

### PR DESCRIPTION
**Pull request by dg1sbg**
Could you please review this PR and provide feedback? Thanks!

Frank

### CODE REVIEW

**Comment by luismbo** [comment]
Hi @dg1sbg. As requested (~2 years ago), here's my review. I've pushed some changes, notably finalizer support, albeit untested. Can you take it for a spin?

**Comment by Shinmera** [comment]
It loads, at least that much I can confirm for now.

**Comment by luismbo** [comment]
@Shinmera Thanks! `(asdf:load-system :trivial-garbage-tests)` followed by `(trivial-garbage-tests:run)` will run the test suite.

**Comment by Shinmera** [comment]
Well, it's not looking too rosy.
```
COMMON-LISP-USER> (asdf:test-system :trivial-garbage)
;;; Warning: System definition file #P"/media/DATA/Projects/cl/trivial-garbage/trivial-garbage.asd" contains definition for system "trivial-garbage-tests". Please only define "trivial-garbage" and secondary systems with a name starting with "trivial-garbage/" (e.g. "trivial-garbage/test") in that file.
;;; Warning: Deprecated recursive use of (ASDF/OPERATE:OPERATE
             'ASDF/LISP-ACTION:TEST-OP '("trivial-garbage-tests")) while
             visiting (ASDF/LISP-ACTION:TEST-OP "trivial-garbage") - please use
             proper dependencies instead
;;; Warning: System definition file #P"/media/DATA/Projects/cl/trivial-garbage/trivial-garbage.asd" contains definition for system "trivial-garbage-tests". Please only define "trivial-garbage" and secondary systems with a name starting with "trivial-garbage/" (e.g. "trivial-garbage/test") in that file.
;;; Warning: Computing just-done stamp in plan NIL for action (ASDF/LISP-ACTION:PREPARE-OP
                                                               "trivial-garbage-tests"), but dependency (ASDF/LISP-ACTION:LOAD-OP
                                                                                                         "trivial-garbage") wasn't done yet!
;;; Warning: Deprecated recursive use of (ASDF/OPERATE:OPERATE
             'ASDF/LISP-ACTION:LOAD-OP '("trivial-garbage-tests")) while
             visiting (ASDF/LISP-ACTION:TEST-OP "trivial-garbage-tests") -
             please use proper dependencies instead

Doing 11 pending tests of 11 tests total.
Only objectp() objects can be added to Mapping
../../src/main/main.cc:269 There was an unhandled exception - do something about it.
[1]    27475 abort (core dumped)  ./clasp
```

**Comment by drmeister** [comment]
The crash is due to this:

(deftest pointers.1
    (weak-pointer-p (make-weak-pointer 42))
  t)

In clasp - you can't make a weak-pointer to an immediate fixnum.
I need to think on what to do here.

**Comment by luismbo** [comment]
@drmeister on the one hand the test is a bit silly; on the other hand, crashing seems harsh. In any case, I don't mind changing the test to something else, perhaps a string?

**Comment by luismbo** [comment]
@drmeister Thinking about it a little bit more, I suppose one thing you could do with immediate objects is to return a weak pointer object but don't bother registering it with the GC?

**Comment by drmeister** [comment]
Yes - crashing is unacceptable - I'll fix that.

Does clasp need to support weak pointers to immediate objects in order to be compatible with trivial-garbage?

A string should work perfectly well with Clasp.

I discovered more about the problem.  
Clasp supports two garbage collectors: boehm and MPS.
The current discussion is on the boehm collector.   The problem with weak pointers to immediate objects is that when boehm splats a weak pointer boehm writes a NULL (0x0) into the word.   This is recognized by Clasp as the fixnum 0 (zero).

I warned myself about this.
https://github.com/clasp-developers/clasp/blob/dev/src/core/weakPointer.cc#L48

This may be a hard problem to solve with boehm - I may get clues for how to solve it from ECL, which also uses boehm.
It will be a completely different situation for MPS.   We plan to use MPS as our standard garbage collector and boehm would only be used for bootstrapping. So I am thinking about disabling weak pointers with the boehm gc.

**Comment by luismbo** [comment]
@drmeister `make-weak-pointer` already rejects `nil` for similar reasons, but I'm not sure how we could make it reject immediate objects portably. I don't mind documenting this as a (minor) known Clasp issue. I'll change the test to use a string.

Later on, when Clasp stops crashing with immediate objects I can add back the original test and mark it as an unexpected failure or something. Let me know what you decide to do.

@Shinmera if you change the test to use "42" instead of 42, does the rest of the suite run to completion?

**Comment by drmeister** [comment]
Hmm,  what if clasp's make-weak-pointer rejected fixnum 0?  Or all fixnums?

I acknowledge that this suggestion sounds a bit weird.

**Comment by luismbo** [comment]
@drmeister Works for me. Wouldn't other immediate objects (e.g., floats? NIL?) have similar issues though?

**Comment by drmeister** [comment]
I came up with another idea.  I'll add a flag to tell me if the value is a pointer or not.  Only pointers can be splatted and 0x0 will mean the pointer was splatted.   For immediate values I won't tell the GC to do anything with them.

**Comment by luismbo** [comment]
@drmeister Sounds good. Seems similar to what I was going for with my previous suggestion: https://github.com/trivial-garbage/trivial-garbage/pull/12#issuecomment-421358093. It seems better than what (I think) SBCL does: weak pointers to immediate the objects get added to the global weak pointer list and then keep being ignored since they fail the [`weak_pointer_breakable_p()`/`is_lisp_pointer()` test](https://github.com/sbcl/sbcl/blob/ebdb9ef98a4039b5b95ec5491b871456cb19379f/src/runtime/gc-private.h#L162
).

**Comment by luismbo** [comment]
@drmeister as I understand it, your latest plan should mean that this pull request is good to go. I can merge it and release a new version of trivial-garbage once you give me the green light and confirm that the test suite passes.

**Comment by Shinmera** [comment]
That's how I see it too. The current version works fine for all practical intents and purposes.

**Comment by luismbo** [comment]
@Shinmera https://github.com/trivial-garbage/trivial-garbage/releases/tag/v0.21 is released. I hope I didn't jump the gun. :-) I misread your message as confirmation that the test suite passes.

**Pull request merged**
